package ca.sheridancollege.medreminder.presentation.emergency

import android.content.Context
import android.content.Intent
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import ca.sheridancollege.medreminder.data.datastore.UserPreferencesDataStore
import ca.sheridancollege.medreminder.data.repository.MedicationRepository
import ca.sheridancollege.medreminder.domain.model.Medication
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import javax.inject.Inject

data class EmergencyUiState(
    val emergencyName: String = "",
    val emergencyPhone: String = "",
    val emergencyRelation: String = "",
    val bloodType: String = "",
    val conditions: String = "",
    val allergies: String = "",
    val medications: List<Medication> = emptyList()
)

@HiltViewModel
class EmergencyViewModel @Inject constructor(
    private val dataStore: UserPreferencesDataStore,
    private val repository: MedicationRepository
) : ViewModel() {

    val uiState: StateFlow<EmergencyUiState> = combine(
        combine(
            dataStore.emergencyContactName,
            dataStore.emergencyContactPhone,
            dataStore.emergencyContactRelation,
            dataStore.userBloodType,
            dataStore.userMedicalConditions
        ) { name, phone, relation, blood, conditions ->
            listOf(name, phone, relation, blood, conditions)
        },
        dataStore.userAllergies,
        repository.getAllActiveMedications()
    ) { baseInfo, allergies, meds ->
        EmergencyUiState(
            emergencyName = baseInfo[0],
            emergencyPhone = baseInfo[1],
            emergencyRelation = baseInfo[2],
            bloodType = baseInfo[3],
            conditions = baseInfo[4],
            allergies = allergies,
            medications = meds
        )
    }.stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), EmergencyUiState())

    fun saveEmergencyContact(name: String, phone: String, relation: String) {
        viewModelScope.launch { dataStore.setEmergencyContact(name, phone, relation) }
    }

    fun saveMedicalInfo(bloodType: String, conditions: String, allergies: String) {
        viewModelScope.launch { dataStore.setMedicalInfo(bloodType, conditions, allergies) }
    }

    fun sendEmergencySms(context: Context) {
        val state = uiState.value
        if (state.emergencyPhone.isBlank()) return

        val medList = state.medications.joinToString("\n") {
            "• ${it.name} ${it.dosage} at ${it.formattedTime()}"
        }

        val message = """
🚨 EMERGENCY ALERT from MedReminder

Patient needs immediate assistance.

🩸 Blood Type: ${state.bloodType.ifBlank { "Unknown" }}
🏥 Conditions: ${state.conditions.ifBlank { "None on record" }}
⚠️ Allergies: ${state.allergies.ifBlank { "None on record" }}

💊 Current Medications:
$medList

Please call or go to them immediately.
        """.trimIndent()

        try {
            val smsManager = context.getSystemService(android.telephony.SmsManager::class.java)
            val parts = smsManager.divideMessage(message)
            smsManager.sendMultipartTextMessage(state.emergencyPhone, null, parts, null, null)
        } catch (e: Exception) {
            // Fallback to SMS intent
            val intent = Intent(Intent.ACTION_SENDTO, android.net.Uri.parse("smsto:${state.emergencyPhone}")).apply {
                putExtra("sms_body", message)
                flags = Intent.FLAG_ACTIVITY_NEW_TASK
            }
            context.startActivity(intent)
        }
    }

    fun shareMedicationList(context: Context) {
        val state = uiState.value
        val medList = state.medications.joinToString("\n") {
            "• ${it.name} — ${it.dosage} — ${it.formattedTime()} — Days: ${it.days.joinToString(", ") { d -> d.displayName }}"
        }

        val text = """
MEDICAL INFORMATION CARD
Generated by MedReminder

🩸 Blood Type: ${state.bloodType.ifBlank { "Unknown" }}
🏥 Medical Conditions: ${state.conditions.ifBlank { "None" }}
⚠️ Allergies: ${state.allergies.ifBlank { "None" }}

💊 CURRENT MEDICATIONS:
$medList

Emergency Contact: ${state.emergencyName} (${state.emergencyRelation}) — ${state.emergencyPhone}
        """.trimIndent()

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
            putExtra(Intent.EXTRA_SUBJECT, "My Medical Information")
            flags = Intent.FLAG_ACTIVITY_NEW_TASK
        }
        context.startActivity(Intent.createChooser(intent, "Share Medical Info").apply {
            flags = Intent.FLAG_ACTIVITY_NEW_TASK
        })
    }
}
